FROM node:20-bookworm

RUN echo '#!/bin/bash \n\n\
    alias ls="ls --color=auto" \n\
    ' > /home/node/.bash_aliases

RUN DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install vim curl git tini

RUN mkdir /home/node/src
WORKDIR /home/node/src
USER node

ENTRYPOINT ["tini", "--"]
CMD ["/bin/bash"]